import type { Metadata } from "next";
import Sidebar from "./Sidebar/page";
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="grid-flow-col">
                <Sidebar/>
              {children}
            </body>
        </html>
    );
}
