"use client";
import React, { useState } from "react";
// import type { Metadata } from "next";
import Sidebar from "./Sidebar/page";
import Background from "../../../public/assets/bg.png";
import Image from "next/image";

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const [isSidebarOpen, setIsSidebarOpen] = useState(false);
    const toggleSidebar = () => {
        setIsSidebarOpen(!isSidebarOpen);
    };

    return (
        <html lang="en">
            <body className=" h-screen w-screen overflow-hidden">
                {/* <div className="hidden lg:block lg:absolute">
                    <Image src={Background} alt="background" />
                </div>
                <button
                    className="lg:hidden absolute top-0 left-0 m-4"
                    onClick={toggleSidebar}
                >
                    Menu
                </button> */}
                <div className="flex flex-col lg:flex-row h-screen">
                    <Sidebar isOpen={isSidebarOpen} />
                    <div className="flex-grow h-full overflow-y-auto">
                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}
